# http://docs.travis-ci.com

language: php
php:
  - "5.6"
before_install:
  - composer --version
  - git --version
  - node --version
  - npm --version
before_script:
  - composer install
  - npm install
script:
  - ./vendor/bin/phpcs --standard=PSR1,PSR2 src -x!*.js
  - grunt setup --verbose
