# http://docs.travis-ci.com

language: php
php:
  - "5.6"
node_js:
  - "6"
before_install:
  - composer --version
before_script:
  - composer install
script:
  - ./vendor/bin/phpcs --standard=PSR1,PSR2 src/lib src/setup
  - grunt setup --verbose
sudo: false
